name: WealthPulse
options:
  bundleIdPrefix: com.ggsheng
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: "9L6N2ZF26B"
    CODE_SIGN_STYLE: Automatic
    ENABLE_USER_SCRIPT_SANDBOXING: NO

packages:
  SnapKit:
    url: https://github.com/SnapKit/SnapKit
    from: "5.6.0"

targets:
  WealthPulse:
    type: application
    platform: iOS
    sources:
      - path: WealthPulse/Sources
      - path: WealthPulse/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ggsheng.WealthPulse
        INFOPLIST_FILE: WealthPulse/Sources/App/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: WealthPulse/Sources/App/WealthPulse.entitlements
        GENERATE_INFOPLIST_FILE: NO
    dependencies:
      - package: SnapKit
    entitlements:
      path: WealthPulse/Sources/App/WealthPulse.entitlements
      properties: {}

  WealthPulseTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: WealthPulseTests
    settings:
      base:
        INFOPLIST_FILE: WealthPulseTests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.ggsheng.WealthPulseTests
        PRODUCT_NAME: WealthPulseTests
        GENERATE_INFOPLIST_FILE: NO
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/WealthPulse.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/WealthPulse"
        BUNDLE_LOADER: "$(TEST_HOST)"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: "9L6N2ZF26B"
    dependencies:
      - target: WealthPulse

  WealthPulseUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: WealthPulseUITests
    settings:
      base:
        INFOPLIST_FILE: WealthPulseUITests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.ggsheng.WealthPulseUITests
        PRODUCT_NAME: WealthPulseUITests
        GENERATE_INFOPLIST_FILE: NO
        TEST_TARGET: "$(BUILT_PRODUCTS_DIR)/WealthPulse.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/WealthPulse"
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: ""
        DEVELOPMENT_TEAM: "9L6N2ZF26B"
    dependencies:
      - target: WealthPulse

schemes:
  WealthPulse:
    build:
      targets:
        WealthPulse: all
        WealthPulseTests: test
        WealthPulseUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - WealthPulseUITests
    archive:
      config: Release
